import { useState } from "react";
type View="paired"|"assembly"|"vaf"|"typing"|"files";
const labels:Record<View,string>={paired:"Paired-end reads",assembly:"Alignment vs assembly",vaf:"VAF + mixtures",typing:"SNP vs cgMLST",files:"Files through a pipeline"};
export function GenomicsConceptGallery(){
 const [view,setView]=useState<View>("assembly");
 return <section className="concept-figure genomics-gallery" aria-labelledby="genomics-gallery-title">
  <p className="eyebrow">Original visual atlas</p><h3 id="genomics-gallery-title">Five genomic concepts worth seeing</h3>
  <p className="figure-lede">Switch views to connect sequencing vocabulary with the information structure each term describes. All examples are synthetic.</p>
  <div className="gallery-tabs" role="group" aria-label="Genomics concept">{(Object.keys(labels) as View[]).map(k=><button type="button" key={k} className={view===k?"active":""} aria-pressed={view===k} onClick={()=>setView(k)}>{labels[k]}</button>)}</div>
  <div className="gallery-canvas">
   {view==="paired"&&<><div className="paired-figure"><div className="fragment"><span className="read-left">read 1 →</span><i>unsequenced / inferred insert</i><span className="read-right">← read 2</span></div></div><p><strong>Paired-end:</strong> two reads come from opposite ends of the same DNA fragment. The pairing adds positional information beyond either read alone.</p></>}
   {view==="assembly"&&<><div className="assembly-grid"><div><small>Reference alignment</small><div className="gallery-reference-line">known reference</div><span className="read r1"/><span className="read r2"/><span className="read r3"/></div><div><small>De novo assembly</small><div className="loose-reads"><span/><span/><span/><span/></div><div className="contig">overlap → assembled contig</div></div></div><p><strong>Different questions:</strong> alignment asks where reads fit relative to a chosen reference; de novo assembly reconstructs longer sequence from read overlaps without requiring that same coordinate scaffold.</p></>}
   {view==="vaf"&&<><div className="vaf-stack">{Array.from({length:10},(_,i)=><span key={i} className={i<3?"alt":""}>{i<3?"G":"A"}</span>)}</div><p><strong>30% VAF:</strong> three of ten illustrative reads support G at this position. That does not by itself prove “30% strain B,” heterozygosity, or a new strain. Mixture, within-host diversity, contamination, and technical effects are among possibilities requiring context.</p></>}
   {view==="typing"&&<><div className="typing-grid"><div><small>SNP-based comparison</small><div className="sequence-row">A C G <b>T</b> A C G</div><div className="sequence-row">A C G <b>C</b> A C G</div><span>compare high-confidence nucleotide differences across comparable positions</span></div><div><small>cgMLST</small><div className="alleles"><b>locus 1: 14</b><b>locus 2: 8</b><b>locus 3: 31</b></div><span>compare allele assignments across a defined core-gene scheme</span></div></div><p><strong>Do not interchange the distances.</strong> SNP counts and allele differences arise from different analytical frameworks; interpretation depends on organism, method, quality, scheme/reference, filters, and epidemiologic context.</p></>}
   {view==="files"&&<><div className="file-pipeline"><span><b>FASTQ</b><small>reads + quality</small></span><b>→</b><span><b>Alignment / assembly</b><small>analysis step</small></span><b>→</b><span><b>BAM/CRAM</b><small>alignment-oriented records*</small></span><b>→</b><span><b>Variant calling</b><small>analysis step</small></span><b>→</b><span><b>VCF</b><small>variant records</small></span></div><p><strong>Files preserve different layers of evidence.</strong> This is a simplified alignment/variant-calling pathway; assembly workflows can produce other outputs such as contig FASTA files. BAM/CRAM can also represent unmapped records; file type alone does not establish analytical validity.</p></>}
  </div>
 </section>
}
